import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as Y from 'yjs';
import { addCard, createCard, patchCard, readCards, newRoom, parseInvite, inviteFor, queuePayload, parseReceipts, cardSchema } from '../src/model';
import { analyzeLocal, initializeDictionary } from '../src/language';
import { readFileSync } from 'node:fs';
initializeDictionary(JSON.parse(readFileSync(new URL('../public/dictionary.js',import.meta.url),'utf8').replace('globalThis.JYUTBOARD_DICTIONARY=','').replace(/;\s*$/,'')));

test('Cantonese lookup gives Jyutping and meaningful multi-character words offline',()=>{const result=analyzeLocal('我想飲水。');assert.match(result.jyutping,/ngo5 soeng2 jam2 seoi2/);assert.equal(result.definition,'I would like some water.');assert.ok(result.words.some(w=>w.definition.includes('drink')));const advanced=analyzeLocal('圖書館');assert.ok(advanced.words.some(w=>w.definition.includes('library')));});
test('separate card fields survive concurrent offline edits and converge',()=>{const a=new Y.Doc(),b=new Y.Doc();const card=createCard({chinese:'你好'});addCard(a,card);Y.applyUpdate(b,Y.encodeStateAsUpdate(a));patchCard(a,card.id,{x:300,starred:true});patchCard(b,card.id,{definition:'Hello!',audio:'data:audio/webm;base64,YQ=='});const au=Y.encodeStateAsUpdate(a),bu=Y.encodeStateAsUpdate(b);Y.applyUpdate(a,bu);Y.applyUpdate(b,au);assert.deepEqual(readCards(a),readCards(b));assert.equal(readCards(a)[0].x,300);assert.equal(readCards(a)[0].definition,'Hello!');assert.equal(readCards(a)[0].starred,true);a.destroy();b.destroy();});
test('deleted cards do not reappear from stale reconnects',()=>{const a=new Y.Doc(),b=new Y.Doc();const card=createCard();addCard(a,card);Y.applyUpdate(b,Y.encodeStateAsUpdate(a));a.getMap('cards').delete(card.id);patchCard(b,card.id,{definition:'late edit'});Y.applyUpdate(a,Y.encodeStateAsUpdate(b));assert.equal(readCards(a).length,0);a.destroy();b.destroy();});
test('invites round trip and reject invalid protocols, credentials, and weak room codes',()=>{const room=newRoom();const invite=inviteFor(room,'wss://relay.example.com');assert.deepEqual(parseInvite(invite),{room,relay:'wss://relay.example.com'});assert.throws(()=>parseInvite('https://example.com'));assert.throws(()=>inviteFor('guessable','wss://relay.example.com'));assert.throws(()=>inviteFor(room,'file:///tmp/test'));assert.throws(()=>inviteFor(room,'ws://user:password@host'));});
test('queue requests use the documented envelope and do not pretend to upload audio',()=>{const card=createCard({chinese:'我想飲水',audio:'data:audio/webm;base64,YQ=='});const session={id:newRoom(),title:'Tea time',created:Date.now()};const payload=queuePayload([card],session);assert.equal(payload.requests[0].chinese,card.chinese);assert.equal(payload.requests[0].metadata.hasLessonRecording,true);assert.equal(JSON.stringify(payload).includes('data:audio'),false);assert.deepEqual(payload,queuePayload([card],session));});
test('HTTP 207 receipts retain failed and conflicting items, and missing entries fail closed',()=>{const receipts=parseReceipts({results:[{index:2,status:'conflict',message:'changed fields'},{index:0,status:'created',id:'abc'},{index:1,status:'failed'}]},4);assert.deepEqual(receipts,['created','failed','conflict: changed fields','failed: Missing or ambiguous queue receipt']);});
test('invalid peer data cannot inject arbitrary playable URLs or infinite coordinates',()=>{assert.equal(cardSchema.safeParse(createCard({audio:'https://evil.example/track',x:Infinity})).success,false);const doc=new Y.Doc();doc.getMap('cards').set('bad',{x:Infinity});assert.deepEqual(readCards(doc),[]);doc.destroy();});
