import { useEffect, useRef, useState } from 'react';
import { Mic, Square, Upload } from 'lucide-react';
import { MAX_AUDIO } from './model';
export function AudioRecorder({audio,onAudio,notify}:{audio?:string;onAudio:(data:string,name:string)=>void;notify:(text:string)=>void}){
 const [recording,setRecording]=useState(false);const recorder=useRef<MediaRecorder|null>(null);const stream=useRef<MediaStream|null>(null);const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const input=useRef<HTMLInputElement>(null);const mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;clearTimeout(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());};},[]);
 async function attach(blob:Blob,name:string){if(blob.size>MAX_AUDIO){notify('Recording is too large. Keep clips under 2 MB (about 60 seconds).');return;}if(!blob.size){notify('No audio was captured. Please try again.');return;}const reader=new FileReader();reader.onload=()=>{if(mounted.current)onAudio(String(reader.result),name);};reader.readAsDataURL(blob);}
 async function start(){try{if(window.desktop&&!await window.desktop.microphone())throw Error('Allow microphone access in system settings, then try again.');const media=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});if(!mounted.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;const mime=['audio/webm;codecs=opus','audio/mp4'].find(x=>MediaRecorder.isTypeSupported(x));const r=new MediaRecorder(media,mime?{mimeType:mime,audioBitsPerSecond:48000}:undefined);recorder.current=r;const chunks:Blob[]=[];r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};r.onerror=()=>notify('Recording failed. Check your microphone and retry.');r.onstop=()=>{clearTimeout(timer.current);media.getTracks().forEach(t=>t.stop());if(mounted.current){setRecording(false);void attach(new Blob(chunks,{type:r.mimeType}),'Natasha’s pronunciation');}};r.start();setRecording(true);timer.current=setTimeout(()=>{if(r.state==='recording')r.stop();},60000);}catch(error){notify(error instanceof Error?error.message:'Microphone unavailable');}}
 return <div className="recording"><div className="row"><button className={recording?'danger':'soft'} onClick={()=>recording?recorder.current?.stop():void start()}>{recording?<Square size={15}/>:<Mic size={15}/>} {recording?'Stop recording':'Record Natasha'}</button><button title="Attach an audio file" aria-label="Attach an audio file" onClick={()=>input.current?.click()}><Upload size={15}/></button><input hidden ref={input} type="file" accept="audio/*" onChange={e=>{const file=e.target.files?.[0];if(file){if(!file.type.startsWith('audio/'))notify('Choose an audio file.');else void attach(file,file.name);}e.target.value='';}}/></div>{recording?<small className="recording-label">● Recording · stops after 60 seconds</small>:null}{audio?<audio controls src={audio} preload="metadata"/>:null}</div>;
}
